# Generated by Django 3.1.5 on 2021-01-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seas.sea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
