# Generated by Django 3.1.5 on 2021-01-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('pkk', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beaches', to='seas.sea')),
            ],
        ),
    ]
