# Generated by Django 3.1.5 on 2021-01-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seas', '0001_initial'),
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='sea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beaches', to='seas.sea'),
        ),
    ]
