# Generated by Django 3.1.5 on 2021-01-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('pkk', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
