# Generated by Django 3.1.5 on 2021-01-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=300)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='beaches.beach')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
